<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StageTrack.Domain\StageTrack.Domain.csproj" />
    <ProjectReference Include="..\StageTrack.Application.Contracts\StageTrack.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
  </ItemGroup>


</Project>
